import assert from "node:assert/strict";
import test from "node:test";

import {
  cleanChannelName,
  parseYouTubeTrack,
  stripVideoNoise,
} from "./youtube-track-parser.ts";

test("reads song, artists and album from an auto-generated description", () => {
  const description = [
    "Provided to YouTube by Sony Music Entertainment",
    "",
    "De Música Ligera · Soda Stereo",
    "",
    "Canción Animal",
    "",
    "℗ 1990 Sony Music Entertainment Argentina S.A.",
    "",
    "Released on: 1990-08-07",
    "",
    "Auto-generated by YouTube.",
  ].join("\n");

  assert.deepEqual(
    parseYouTubeTrack({
      title: "De Música Ligera",
      description,
      videoOwnerChannelTitle: "Soda Stereo - Topic",
    }),
    {
      name: "De Música Ligera",
      artists: ["Soda Stereo"],
      album: "Canción Animal",
    },
  );
});

test("keeps every artist of an auto-generated description", () => {
  const description =
    "Provided to YouTube by UMG\r\n\r\nUnder Pressure · Queen · David Bowie\r\n\r\nHot Space\r\n\r\n℗ 1982";

  assert.deepEqual(parseYouTubeTrack({ title: "Under Pressure", description }), {
    name: "Under Pressure",
    artists: ["Queen", "David Bowie"],
    album: "Hot Space",
  });
});

test("album is null when the description jumps straight to the copyright", () => {
  const description = "Provided to YouTube by X\n\nSong · Artist\n\n℗ 2020 X";
  assert.equal(parseYouTubeTrack({ title: "Song", description }).album, null);
});

test("falls back to the Topic channel for the artist", () => {
  assert.deepEqual(
    parseYouTubeTrack({
      title: "Persiana Americana",
      description: "",
      videoOwnerChannelTitle: "Soda Stereo - Topic",
    }),
    { name: "Persiana Americana", artists: ["Soda Stereo"], album: null },
  );
});

test("splits 'Artist - Song' and removes the video noise", () => {
  assert.deepEqual(
    parseYouTubeTrack({
      title: "Gustavo Cerati - Crimen (Official Video)",
      videoOwnerChannelTitle: "GustavoCeratiVEVO",
    }),
    { name: "Crimen", artists: ["Gustavo Cerati"], album: null },
  );
});

test("uses the uploader when the title has no dash", () => {
  assert.deepEqual(
    parseYouTubeTrack({
      title: "Bohemian Rhapsody [Official Music Video]",
      videoOwnerChannelTitle: "QueenVEVO",
    }),
    { name: "Bohemian Rhapsody", artists: ["Queen"], album: null },
  );
});

test("skips deleted and private videos", () => {
  assert.equal(parseYouTubeTrack({ title: "Deleted video" }), null);
  assert.equal(parseYouTubeTrack({ title: "Private video" }), null);
  assert.equal(parseYouTubeTrack({ title: "" }), null);
});

const noisy = [
  ["Song (Official Video)", "Song"],
  ["Song (Official Music Video)", "Song"],
  ["Song [Official Audio]", "Song"],
  ["Song (Lyrics)", "Song"],
  ["Song (Lyric Video)", "Song"],
  ["Song (Video Oficial)", "Song"],
  ["Song (Official Visualizer)", "Song"],
  ["Song [HD]", "Song"],
  ["Song (Official 4K Video)", "Song"],
  ["Song | Official Video", "Song"],
  ["Song - Official Audio", "Song"],
  ["Song (Official Video) [HD]", "Song"],
];

for (const [input, expected] of noisy) {
  test(`strips video noise from ${JSON.stringify(input)}`, () => {
    assert.equal(stripVideoNoise(input), expected);
  });
}

const meaningful = [
  "Song (Live)",
  "Song (Acoustic Version)",
  "Song (feat. Someone)",
  "Song (Remix)",
  "Video Killed the Radio Star",
  "Official",
];

for (const input of meaningful) {
  test(`keeps ${JSON.stringify(input)}`, () => {
    assert.equal(stripVideoNoise(input), input);
  });
}

test("cleans channel names", () => {
  assert.equal(cleanChannelName("Adele - Topic"), "Adele");
  assert.equal(cleanChannelName("TaylorSwiftVEVO"), "Taylor Swift");
  assert.equal(cleanChannelName("ACDCVEVO"), "ACDC");
  assert.equal(cleanChannelName("Los Fabulosos Cadillacs"), "Los Fabulosos Cadillacs");
});
