/**
 * Turns a YouTube playlist item into a song: name, artists and album.
 *
 * The YouTube Data API has no notion of "track". What it gives us is a video
 * title, its description and the uploader channel. Two sources are used, best first:
 *
 * 1. Auto-generated "Topic" videos (the ones YouTube Music plays for album
 *    tracks) carry a machine-written description:
 *
 *        Provided to YouTube by <label>
 *
 *        <Song> · <Artist> · <Artist>
 *
 *        <Album>
 *
 *        ℗ 2019 <label>
 *
 *    That gives the real title, every artist and the album.
 *
 * 2. Anything else (official videos, uploads): "Artist - Song (Official Video)"
 *    is split on the dash and the video noise is removed. Without a dash, the
 *    uploader channel is the best guess for the artist.
 *
 * Kept free of imports so `node --test` can load it directly.
 */

export type YouTubeItemSnippet = {
  title?: string | null;
  description?: string | null;
  /** Missing for deleted and private videos. */
  videoOwnerChannelTitle?: string | null;
};

export type ParsedTrack = {
  name: string;
  artists: string[];
  album: string | null;
};

/** Placeholders YouTube returns in place of videos the user can no longer see. */
const UNAVAILABLE_TITLES = new Set(["deleted video", "private video"]);

const PROVIDED_BY = /^provided to youtube by\b/i;
const ARTIST_SEPARATOR = " · ";
/** Lines after the album in the auto-generated description. */
const DESCRIPTION_METADATA =
  /^(?:℗|©|\(p\)|\(c\)|released on:|auto-generated by youtube|composer:|lyricist:|producer:|associated performer:)/i;

const VIDEO_NOISE_WORDS = [
  String.raw`official`,
  String.raw`oficial`,
  String.raw`(?:music\s+|lyrics?\s+)?video(?:clip)?`,
  String.raw`v[ií]deo(?:clip)?`,
  String.raw`clip`,
  String.raw`audio`,
  String.raw`lyrics?`,
  String.raw`letra`,
  String.raw`visuali[sz]er`,
  String.raw`m\/?v`,
  String.raw`hd`,
  String.raw`hq`,
  String.raw`4k`,
];

/** A bracketed qualifier made ONLY of video noise: "(Official Music Video)", "[HD]". */
const BRACKETED_NOISE = new RegExp(
  String.raw`\s*[(\[](?:\s*(?:` +
    VIDEO_NOISE_WORDS.join("|") +
    String.raw`)[\s/&,|-]*)+[)\]]`,
  "giu",
);

/** "Song | Official Video", "Song - Official Audio". */
const TRAILING_NOISE = new RegExp(
  String.raw`\s+[|\-–—]\s*(?:(?:` +
    VIDEO_NOISE_WORDS.join("|") +
    String.raw`)\s*)+$`,
  "iu",
);

const TITLE_SEPARATOR = /^(.+?)\s+[-–—]\s+(.+)$/u;

/** Exact suffix of YouTube's auto-generated artist channels. */
const TOPIC_SUFFIX = /\s+-\s+topic$/iu;
/** Looser form for cleaning names: "Name Topic", "Name - Topic", "Name – Topic". */
const TOPIC_NOISE = /\s*[-–—]?\s*\btopic$/iu;
const VEVO_SUFFIX = /\s*vevo$/iu;

function isUnavailable(snippet: YouTubeItemSnippet) {
  const title = snippet.title?.trim().toLowerCase() ?? "";
  return !title || (UNAVAILABLE_TITLES.has(title) && !snippet.videoOwnerChannelTitle);
}

/** "Adele - Topic" / "Adele Topic" -> "Adele", "TaylorSwiftVEVO" -> "Taylor Swift". */
export function cleanChannelName(channel: string): string {
  const trimmed = channel.trim();
  if (TOPIC_NOISE.test(trimmed)) {
    const base = trimmed.replace(TOPIC_NOISE, "").trim();
    // A channel literally called "Topic" keeps its name.
    if (base) return base;
  }

  if (VEVO_SUFFIX.test(trimmed)) {
    const base = trimmed.replace(VEVO_SUFFIX, "");
    // VEVO channels glue the words together; split camel case only when there
    // are no spaces at all, so "ACDC" or "Guns N' Roses" are left alone.
    return base.includes(" ")
      ? base
      : base.replace(/(\p{Ll})(\p{Lu})/gu, "$1 $2");
  }

  return trimmed;
}

/** Removes "(Official Video)", "[HD]", "| Official Audio" and similar from a video title. */
export function stripVideoNoise(title: string): string {
  const cleaned = title
    .replace(BRACKETED_NOISE, "")
    .replace(TRAILING_NOISE, "")
    .replace(/\s{2,}/gu, " ")
    .trim();

  return cleaned || title.trim();
}

function parseAutoGeneratedDescription(
  description: string,
): ParsedTrack | null {
  const lines = description
    .split(/\r?\n/u)
    .map((line) => line.trim())
    .filter(Boolean);

  if (!lines[0] || !PROVIDED_BY.test(lines[0]) || !lines[1]) return null;

  const [name, ...artists] = lines[1].split(ARTIST_SEPARATOR).map((part) => part.trim());
  if (!name || artists.length === 0) return null;

  const albumLine = lines[2];
  const album =
    albumLine && !DESCRIPTION_METADATA.test(albumLine) ? albumLine : null;

  return { name, artists: artists.filter(Boolean), album };
}

export function parseYouTubeTrack(
  snippet: YouTubeItemSnippet,
): ParsedTrack | null {
  if (isUnavailable(snippet)) return null;

  const fromDescription = snippet.description
    ? parseAutoGeneratedDescription(snippet.description)
    : null;
  if (fromDescription) return fromDescription;

  const channel = snippet.videoOwnerChannelTitle?.trim() ?? "";
  const title = stripVideoNoise(snippet.title ?? "");

  // Topic channels title the video with the bare song name.
  if (TOPIC_SUFFIX.test(channel)) {
    return { name: title, artists: [cleanChannelName(channel)], album: null };
  }

  const separated = title.match(TITLE_SEPARATOR);
  if (separated) {
    return {
      name: separated[2].trim(),
      artists: [separated[1].trim()],
      album: null,
    };
  }

  return {
    name: title,
    artists: channel ? [cleanChannelName(channel)] : [],
    album: null,
  };
}
